package co.pextra.botox;

import java.util.List;

import br.ufes.inf.lprm.scene.model.impl.Situation;
import br.ufes.inf.lprm.scene.util.SituationHelper;
import br.ufes.inf.lprm.situation.annotations.part;
import br.ufes.inf.lprm.situation.model.events.*;
import org.kie.api.runtime.process.ProcessInstance;

declare TemperatureSituation extends Situation
    sensor: Sensor @part
    transactions: List @part
end

/*
Verifica se em uma lista de 3 ou mais temperaturas existem temperaturas acima de -3 graus em uma janela de tempo de 2 minutos. 
*/
rule "Ocorreram 3 mudanças de temperatura com o mesmo sensor em um intervalo de 2 minutos"
@role(situation)
@type(TemperatureSituation)
    when
       sensor : Sensor();
       transactions: List(size > 5) from accumulate(
          transaction: TemperatureEvent(sensorId == sensor.sensorId) over window:time (2m),
          collectList(transaction)
       )
     then
       SituationHelper.situationDetected(drools);
end

rule "More than 5 high temperatures in two minutes for a sensor of temperature"
@role(situation)
@type(TemperatureSituation)
    when
       sensor : Sensor();
       transactions: List(size > 3) from accumulate(
          transaction: TemperatureEvent(sensorId == sensor.sensorId, temperature > -3) over window:time (2m),
          collectList(transaction)
       )
     then
       SituationHelper.situationDetected(drools);
end

rule "More than 10 high temperatures in two minutes for a sensor of temperature"
@role(situation)
@type(TemperatureSituation)
    when
       sensor : Sensor();
       transactions: List(size > 6) from accumulate(
          transaction: TemperatureEvent(sensorId == sensor.sensorId, temperature > 0) over window:time (2m),
          collectList(transaction)
       )
     then
       SituationHelper.situationDetected(drools);
end

/*
Se houver mais que 3 situações de elevação de temperatura, em uma janela de tempo de 2 minutos, 
uma ação de notificação de elevação de temperatura é disparada!

## No exemplo exposto são disparados 4 situações de temperaturas acima de -3 graus. vide RuleTest.java##
*/

rule "start botox situation when have a one case suspicious"
	when
       temperatureSituation: List(size > 2) from accumulate (
         Activation($sit: situation, $sit isA TemperatureSituation.class) over window:time (2m);
         collectList($sit)
       )
	then
		//ProcessInstance processInstance = kcontext.getKieRuntime().startProcess("co.pextra.botox.notification");
		System.out.println("uma situação de temperatura ocorreu");
end

/* Criar uma regra que verifica se existem 5 SENSORES (e não ocorrencia de temperatura) em uma janela de tempo de 2 minutos com temperatura elevada.
*
* (...)
*
*
*/
